<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="RolandConverter.Tests\**" />
    <EmbeddedResource Remove="RolandConverter.Tests\**" />
    <None Remove="RolandConverter.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="The Imperial March - Star Wars - Org.mid">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="The Imperial March - Star Wars - Org.seq">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="The Imperial March - Star Wars.mid">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>